# Generated by Django 3.1 on 2020-09-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='name',
            field=models.SlugField(),
        ),
    ]
